name: using-artifacts

on:
  workflow_dispatch:

jobs:
  artifact:
    runs-on: ubuntu-latest
    steps:
    - name: Create Artifact
      run: echo "$(date '+%s') - Artifact test" > "artifact-$(date '+%s').log"

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: my-artifact
        path: ./artifact*
  
  download:
    runs-on: ubuntu-latest
    needs: artifact
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: my-artifact
      
      - name: List
        run: ls -la
        
