name: cache

on:
  workflow_dispatch:

jobs:
  create:
    runs-on: ubuntu-latest

    steps:
    - name: Create file
      run: echo "Timestamp $(date '+%s')" | tee timestamp.txt

    - name: Cache
      uses: actions/cache@v2
      env:
        cache-name: cache-node-modules
      with:
        path: ./timestamp.txt
        key: file-${{ github.run_number }}


  use:
    runs-on: ubuntu-latest
    needs: create
    
    steps:
    - name: List File Before Cache
      run: ls -l
    
    - name: Cache
      uses: actions/cache@v2
      env:
        cache-name: cache-node-modules
      with:
        path: ./timestamp.txt
        key: file-${{ github.run_number }}

    - name: List File After Cache
      run: ls -l

    - name: View File
      run: cat timestamp.txt