name: cache

on:
  workflow_dispatch:

jobs:
  create:
    runs-on: ubuntu-latest

    - name: Cache
      uses: actions/cache@v2
      env:
        cache-name: cache-node-modules
      with:
        path: ./timestamp.txt
        key: abc

    steps:
    - name: Create file
      run: echo "Timestamp $(date '+%s')" | tee timestamp.txt


  use:
    runs-on: ubuntu-latest
    needs: create
    
    steps:
    - run: ls -l
    
    - name: Cache
      uses: actions/cache@v2
      env:
        cache-name: cache-node-modules
      with:
        path: ./timestamp200.txt
        key: abc

    - run: ls -l

    # - name: View File
    #   run: cat timestamp20.txt