name: cache

on:
  workflow_dispatch:

jobs:
  create:
    runs-on: ubuntu-latest

    steps:
    - name: Create file
      run: echo "Timestamp $(date '+%s')" | tee timestamp1.txt

    - name: Cache
      uses: actions/cache@v2
      env:
        cache-name: cache-node-modules
      with:
        path: ./timestamp1.txt
        key: file

  use:
    runs-on: ubuntu-latest
    
    steps:
    - name: Cache
      uses: actions/cache@v2
      env:
        cache-name: cache-node-modules
      with:
        path: ./timestamp2.txt
        key: file
    
    - name: View File
      run: cat timestamp2.txt