name: calling workflow

on:
  workflow_dispatch:

jobs:
  generate-tag:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.generate-image-tag.outputs.tag }}

    steps:
      - name: Set the container tag
        id: generate-image-tag
        run: echo "tag=1.0.0" >> "$GITHUB_OUTPUT"
      
      - name: Display output
        run: echo ${{ steps.generate-image-tag.outputs.tag }}

  call:
    uses: cdivitotawela/github-workflow-examples/.github/workflows/called-workflow.yaml
    with:
      tag: ${{ needs.generate-tag.outputs.tag }}
    needs: ["generate-tag"]
      
    
