# This example shows running commands on different containers
on:
  workflow_dispatch:

jobs:
  container:
    runs-on: ubuntu-latest

    steps:
    - name: Create File
      run: echo "Timestamp $(date '+%s')" | tee timestamp.txt

    - name: Check File
      run: cat timestamp.txt
