name: docker-image

on:
  push:
    branches:
    # Using arbitary branch name to avoid running whenever code is pushed
      # - main
      - docker
  pull_request:
  release:
    types:
    - released

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - run: echo "Event Name $GITHUB_EVENT_NAME"

      - if: ${{ github.event_name == 'release' }}
        run: echo "Create prd tag ${GITHUB_SHA:0:7} ${GITHUB_REF#refs/tags/}"

      - name: Docker Image Build and Publish
        id: docker-build-publish
        if: ${{ github.ref == 'refs/heads/main' || startsWith(github.ref,'refs/tags/') }}
        run: echo "Build and publish"