on:
  push:
    branches:
      - main
  pull_request:
  release:
    types:
    - released

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - run: echo "Event Name $GITHUB_EVENT_NAME"

      - if: ${{ github.event_name == 'release' }}
        run: echo "Create prd tag ${GITHUB_SHA:0:7} ${GITHUB_REF#refs/tags/}"