on:
  push:
    branches:
      - main
  pull_request:
  create:
    tag:

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - run: echo "Event Name $GITHUB_EVENT_NAME"