name: dynamic job gneration

on:
  pull_request:
    paths:
      - dynamic-jobs/**

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs: 
      folders: ${{ steps.changed-files.outputs.all_changed_files }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      # https://github.com/tj-actions/changed-files
      # This action support number of output options
      - name: Changed file list
        uses: tj-actions/changed-files@v45
        id: changed-files
        with:
          dir_names: true
          dir_names_max_depth: 2
          json: true
          matrix: true
          files: |
            dynamic-jobs/**

  execution:
    name: "Execution"
    needs: [changes]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: 
        folder: ${{ fromJSON(needs.changes.outputs.folders) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Execute
        run: ${{ matrix.folder }}/runner.sh
