name: docker-image

on:
  push:
    branches:
    # Using arbitary branch name to avoid running whenever code is pushed
      # - main
      - chrome

jobs:
  chrome:
    runs-on: ubuntu-latest

    container:
      image: node:14-stretch

    steps:
    - uses: browser-actions/setup-chrome@latest
    - run: chrome --version
        