on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Commit hash or branch name'
        required: true
        default: 'main'

jobs:
  release:
    runs-on: ubuntu-latest
    if: ${{ contains(fromJson('["cdivitotawela"]'), github.actor) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.branch }}

      - run: echo "Running Manual trigger"

      - run: git status

      - run: echo ${{ github.actor }}
