name: matrix-docker-test

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Image tag of hyperledger/besu'
        required: true
        default: '24.5.4'

jobs:
  test:
    strategy:
      matrix:
        test:
          - image: besu
            runner: ubuntu-latest
    runs-on: ${{ matrix.test.runner }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - run: |
          docker run -d --rm --name besu hyperledger/besu:${{ inputs.tag }}
          sleep 20
          docker logs besu
          docker stop besu


