name: matrix-docker-test

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Besu version'
        required: true
        default: '24.6.0'

jobs:
  verify:
    strategy:
      matrix:
        combination:
          - tag: ${{ inputs.version }}
            platform: ''
            runner: ubuntu-latest
          - tag: ${{ inputs.version }}-amd64
            platform: 'linux/amd64'
            runner: ubuntu-latest
          - tag: latest
            platform: ''
            runner: ubuntu-latest
          - tag: ${{ inputs.version }}-amd64
            platform: ''
            runner: ubuntu-latest
    runs-on: ${{ matrix.combination.runner }}
    env:
      CONTAINER_NAME: besu-check
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Start container
        run: |
          PLATFORM_OPT=""
          [[ x${{ matrix.combination.platform }} != 'x' ]] && PLATFORM_OPT="--platform ${{ matrix.combination.platform }}"
          docker run -d $PLATFORM_OPT --name ${{ env.CONTAINER_NAME }} hyperledger/besu:${{ matrix.combination.tag }}

      - name: Verify besu container
        run: bash .github/scripts/BesuContainerCheck.sh
        env:
          TAG: ${{ matrix.combination.tag }}
          VERSION: ${{ inputs.version}}
