# This is the job name diplayed on actions tab
name: Multiple Jobs Dependency

on:
  workflow_dispatch:

jobs:
  uat:
    name: UAT
    runs-on: ubuntu-latest

    steps:
    - name: Deploy to UAT
      run: echo "Deploying to UAT"

  prd:
    name: PRD
    needs: uat
    runs-on: ubuntu-latest

    steps:
    - name: Deploy to PRD
      run: echo "Deploying to PRD"
