# Example trigger on release
name: release

on:
  # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#release
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Event triggerred
        run: echo "Event Name [${{ github.event_name }}]"

      - name: Default branch
        run: echo "Default branch [${{ github.event.repository.default_branch }}]"

      - name: Run on release
        if: ${{ github.event_name == 'release' }}
        run: echo "Run this step on release"
      
      - name: Release tag - method 1
        run: echo "${{ github.ref }}" | sed 's|^refs/tags/\(.*\)$|TAGA=\1|g' >> $GITHUB_ENV

      - name: Release tag - method 2
        run: echo "${GITHUB_REF}"

      - name: Release tag - display
        run: |
          echo "Method 1 - ${{ env.TAGA }}"      
