name: conditional-release

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - run: echo github.ref=${{ github.ref }}  github.event=${{ github.event }}

      - if: contains(github.ref, 'refs/heads/release-') || github.ref == 'refs/heads/main'
        run: echo Triggerred

