name: security-scan

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Container image tag'
        required: true
        default: 'develop'      
  schedule:
    # Runs at UTC 8:00am
    - cron:  '0 8 * * *'

jobs:
  scan-sarif:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Vulnerability scanner
        id: trivy
        uses: aquasecurity/trivy-action@0.22.0
        with:
          image-ref: hyperledger/besu:${{ inputs.tag }}
          format: sarif
          output: 'trivy-results.sarif'

      - name: Upload Results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results.sarif'
