name: security-scan

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Container image tag'
        required: false
        default: 'develop'      
  schedule:
    - cron:  '13-17 23 * * *'

jobs:
  scan-sarif:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
 
      - name: Vulnerability scanner
        id: trivy
        uses: aquasecurity/trivy-action@0.22.0
        with:
          image-ref: hyperledger/besu:${TAG:-develop}
          format: sarif
          output: 'trivy-results.sarif'
        env:
          TAG: ${{ inputs.tag }}

      - name: Upload Results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results.sarif'
