name: security-scan

on:
  workflow_dispatch:
    inputs:
      image:
        description: 'Container image including registry path'
        required: true
        default: 'hyperledger/besu'
      tag:
        description: 'Container image tag'
        required: true
        default: 'develop'      

jobs:
  scan-sarif:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Vulnerability scanner
        id: trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ inputs.image }}:${{ inputs.tag }}
          format: sarif
          output: 'trivy-results.sarif'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results.sarif' 

  scan-table:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Vulnerability scanner
        id: trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ inputs.image }}:${{ inputs.tag }}
          format: table
          output: 'trivy-results.sarif'
