name: matrix-docker-test

on:
  push:

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Trigger
        run: echo '{"version":"24.6.0"}' | gh workflow run matrix-docker-test.yaml --json
        env:
          GH_TOKEN:  ${{ github.token }}
