name: using-matrix

on:
  workflow_dispatch:

jobs:
  setup:
    strategy:
      matrix:
        region: ['us-east-1','eu-west-3']
        module: ['ecr-config','ecr-repository']
        include:
          - module: 'ecr-iam'
            region: 'us-east-1'
    runs-on: ubuntu-latest
    steps:
    - run: echo setup ${{ matrix.region }} ${{ matrix.module }}

  deploy:
    needs: ['setup']
    strategy:
      matrix:
        region: ['us-east-1','eu-west-3']
        module: ['ecr-config','ecr-repository']
        include:
          - module: 'ecr-iam'
            region: 'us-east-1'
    runs-on: ubuntu-latest
    steps:
    - run: echo deploy ${{ matrix.region }} ${{ matrix.module }}